#!/usr/bin/env bash
# installs and configure nginx on ubuntu server

sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me https://github.com/Dtikoli permanent;"
sudo sed -i "/listen 80 default_server;/a $line" /etc/nginx/sites-available/default
sudo service nginx restart
