#!/usr/bin/env bash
# fix script to debug nginx port 80, kills nginx master process (though worker processes run)
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
