#!/usr/bin/env bash
# A script that displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

file="/etc/passwd"
while IFS= read -r pline
do
    echo "$pline" | cut -d ":" -f1,3,6
done < "$file"
