#!/usr/bin/env bash
# A script that tells a story based on the contents of the `/etc/passwd` file
myfile="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r pline
do
    f1="$(echo "$pline" | cut -d ":" -f1)"
    f2="$(echo "$pline" | cut -d ":" -f4)"
    f3="$(echo "$pline" | cut -d ":" -f6)"
    f4="$(echo "$pline" | cut -d ":" -f7)"
    f5="$(echo "$pline" | cut -d ":" -f3)"
    f6="$(echo "$pline" | cut -d ":" -f2)"
    f7="$(echo "$pline" | cut -d ":" -f5)"
    echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$myfile"
