#!/usr/bin/env bash
# A script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/task_host
echo "127.0.0.2		localhost" > ~/task_host
echo "8.8.8.8		facebook.com" >> ~/task_host
cp -f ~/task_host /etc/hosts
